// This file is automatically generated. Do not modify it manually.
'use client';
import { useEffect, useState } from 'react';
import { FirebaseProvider } from './provider';
import { initializeFirebase } from '.';

export function FirebaseClientProvider({
  children,
}: {
  children: React.ReactNode;
}) {
  const [firebase, setFirebase] = useState(
    () => initializeFirebase()
  );

  return <FirebaseProvider {...firebase}>{children}</FirebaseProvider>;
}
