// This file is automatically generated. Do not modify it manually.
import {
  type FirebaseApp,
  type FirebaseOptions,
  initializeApp,
} from 'firebase/app';
import { Auth, getAuth } from 'firebase/auth';
import { Firestore, getFirestore } from 'firebase/firestore';
import { firebaseConfig } from './config';
import { isSupported } from 'firebase/analytics';

let firebaseApp: FirebaseApp | undefined;
let auth: Auth | undefined;
let firestore: Firestore | undefined;

function initializeFirebase(options: FirebaseOptions = {}): {
  firebaseApp: FirebaseApp;
  auth: Auth;
  firestore: Firestore;
} {
  if (!firebaseApp) {
    firebaseApp = initializeApp({ ...firebaseConfig, ...options });
    auth = getAuth(firebaseApp);
    firestore = getFirestore(firebaseApp);
  }
  return { firebaseApp, auth: auth!, firestore: firestore! };
}

export { initializeFirebase };

export * from './provider';
export * from './auth/use-user';
